global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 2.0
  publish_frequency: 2.0

  width: 30.0
  height: 15.0
  origin_x: -5.0
  origin_y: -7.5

  plugins:
  #   - {name: static_layer, type: "costmap_2d::StaticLayer"}
  #   # - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: depth_obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
