<?xml version="1.0" ?>
<robot name="tigra" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="length" value="1.85" />
<xacro:property name="width" value="0.75" />
<xacro:property name="heigth" value="0.6" />
<xacro:property name="mass" value="420" />

<xacro:property name="wheel_width" value="0.25" />
<xacro:property name="wheel_radius" value="0.25" />
<xacro:property name="wheel_mass" value="20" />

<xacro:property name="wheelbase" value="1.0" />
<xacro:property name="half_wheelbase" value="${wheelbase/2}" />
<xacro:property name="track_width" value="0.8" />

<xacro:property name="wheel_turn_limit" value="${pi/4}"/>
<xacro:property name="degrees_30" value="${pi/6}"/>
<xacro:property name="mid_wheel_turn_limit" value="${degrees_30}"/>

<xacro:property name="springStiffness" value="125000" />
<xacro:property name="springReference" value="0" />

<xacro:property name="lidar_mass" value="0.1" />
<xacro:property name="lidar_height" value="0.02"/>
<xacro:property name="lidar_radius" value="0.04"/>


<xacro:property name="length" value="1.85" />
<xacro:property name="width" value="0.75" />
<xacro:property name="heigth" value="0.6" />
<xacro:property name="mass" value="420" />
<xacro:property name="wheel_width" value="0.25" />
<xacro:property name="wheel_radius" value="0.25" />
<xacro:property name="wheel_mass" value="20" />
<xacro:property name="wheel_turn_limit" value="${pi/4}" />

<xacro:property name="cam_mass" value="0"/>
<xacro:property name="cam_size" value="0.02" />
  <!-- <xacro:include filename="$(find visual_custom_telemetry)/urdf/circle_overview_bot.gazebo" /> -->

<xacro:property name="degrees_90" value="${pi/2}"/>
<xacro:property name="degrees_180" value="${pi}"/>

<xacro:property name="robot_name" value="tigra" />

<!-- base_footprint - base_link on floor -->
<!-- <link name="base_footprint">
</link>
<gazebo reference="base_footprint"/> -->
  
<xacro:arg name="pub_tf" default="true" />
  
<!-- inertia -->
<xacro:macro name="null_inertial">
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0"
               iyy="0.01" iyz="0"
               izz="0.01"/>
    </inertial>
</xacro:macro>

<xacro:macro name="base_inertial"
               params="width length height mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass * (width * width + height * height) / 12}"
               ixy="0" ixz="0"
               iyy="${mass * (length * length + height * height) / 12}"
               iyz="0"
               izz="${mass * (width * width + length * length) / 12}"/>
    </inertial>
</xacro:macro>

<xacro:macro name="wheel_inertial"
               params="r h mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass / 12 * (3 * r * r + h * h)}" ixy="0.0" ixz="0.0"
               iyy="${mass / 12 * (3 * r * r + h * h)}" iyz="0.0"
               izz="${mass / 2 * r * r}" />
    </inertial> 
</xacro:macro>
 
<!-- xacro base new -->
<link name="base_link">
    <visual>
     	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${length} ${width} ${heigth}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision name="base_collision">
    	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${length} ${width} ${heigth}"/>
        </geometry>
    </collision>
	<xacro:base_inertial
    width="${width}" length="${length}" 
	height="${heigth}" mass="${mass}" >
    <origin xyz="0 0 0" rpy="0 0 0" />
	</xacro:base_inertial>	
</link>


<!-- xacro wheel new -->
<xacro:macro name="wheels" params="name">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertial
          r="${wheel_radius}" h="${wheel_width}"
          mass="${wheel_mass}" >
	  <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      </xacro:wheel_inertial>
    </link>
</xacro:macro>

<!-- speed -->
<xacro:macro name="speed_wheel" params="name base_name xyz ">
    <xacro:wheels name="wheel_${name}" />

    <gazebo reference="${name}_spring_joint">
    	<implicitSpringDamper>true</implicitSpringDamper>
    	<springStiffness>${springStiffness}</springStiffness>
    	<springReference>${springReference}</springReference>
    </gazebo>

    <joint name="${name}_spring_joint" type="prismatic">
    <limit lower="-0.1" upper="0.1" effort="0" velocity="0"/> 
      <parent link="${base_name}"/>
      <child link="spring1_${name}"/>
	  <dynamics damping="0.0" friction="0.0"/>
	  <axis xyz="0 0 1"/>
    </joint>

    <link name="spring1_${name}">
      <xacro:null_inertial/>
    </link>   

    <joint name="${name}_speed_joint" type="continuous">
      <parent link="spring1_${name}"/> 
      <child link="wheel_${name}"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="500.0" velocity="10.0" />
    </joint>
</xacro:macro>

<!-- steer -->
<xacro:macro name="steer_wheel" params="name base_name xyz">
    <xacro:wheels name="wheel_${name}" />
 
    <gazebo reference="${name}_spring_joint">
    	<implicitSpringDamper>true</implicitSpringDamper>
    	<springStiffness>${springStiffness}</springStiffness>
    	<springReference>${springReference}</springReference>
    </gazebo>
    
    <joint name="${name}_spring_joint" type="prismatic">
    <limit lower="-0.1" upper="0.1" effort="0" velocity="0"/>
      <parent link="${base_name}"/>
      <child link="spring2_${name}"/>
	  <dynamics damping="0.0" friction="0.0"/>
	  <axis xyz="0 0 1"/>
    </joint>
   
    <link name="spring2_${name}">
      <xacro:null_inertial/>
    </link>
    
    <joint name="${name}_steer_joint" type="revolute">
      <limit lower="${-wheel_turn_limit}"
             upper="${wheel_turn_limit}"
             effort="1000" velocity="0"/>
      <parent link="spring2_${name}"/>
      <child link="steer_${name}"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

     <link name="steer_${name}">
      <xacro:null_inertial/>
    </link>
    
    <joint name="${name}_speed_joint" type="continuous">
      <parent link="steer_${name}"/>
      <child link="wheel_${name}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="500" velocity="10.0" />
    </joint>
</xacro:macro>


  <!-- <joint name="base_footprint_2_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>

    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint> -->

<gazebo>
	<plugin name="tigra_interface_plugin" filename="libtigra_interface_plugin.so" >
		<robotName>tigra</robotName>
		<maxSteerRad>${mid_wheel_turn_limit}</maxSteerRad>
		<wheelbase>${wheelbase}</wheelbase>
		<wheelRadius>${wheel_radius}</wheelRadius>
		<trackWidth>${track_width}</trackWidth>
		<wheel_rl_joint_>joint_left_wheel_1_speed_joint</wheel_rl_joint_>
		<wheel_rr_joint_>joint_right_wheel_1_speed_joint</wheel_rr_joint_>
		<wheel_fl_joint_>joint_left_wheel_2_speed_joint</wheel_fl_joint_>
		<wheel_fr_joint_>joint_right_wheel_2_speed_joint</wheel_fr_joint_>
	</plugin>
</gazebo>

	<!-- START MACROS FOR VISUAL CAM -->
    <xacro:macro name="camera_link" params="name direction position">
        <link name="${direction}_${position}_cam_frame">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${cam_size} ${cam_size} ${cam_size}" />
                </geometry>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${cam_size} ${cam_size} ${cam_size}" />
                </geometry>
            </collision>

            <inertial>
                <mass value="1e-5" />
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
        </link>
    </xacro:macro>
<!-- END MACROS FOR VISUAL CAM -->


<!-- START MACROS FOR CREATE CAM IN THE GAZEBO -->

    <xacro:macro name="single_camera" params="name direction position xyz rpy fov">

        <xacro:camera_link name="${name}" direction="${direction}" position="${position}" />

        <joint name="${direction}_${position}_joint" type="fixed">
            <child link="${direction}_${position}_cam_frame" />
            <parent link="base_link" />
            <origin xyz="${xyz}" rpy="${rpy}" />
        </joint>

        <link name="${direction}_${position}_optical_frame" />

        <joint name="${direction}_${position}_optical_joint" type="fixed">
            <child link="${direction}_${position}_optical_frame" />
            <parent link="${direction}_${position}_cam_frame" />
            <origin xyz="0 0 0" rpy="-${degrees_90} 0.0 -${degrees_90}" />
        </joint>

        <gazebo reference="${direction}_${position}_cam_frame">
            <material>Gazebo/Orange</material>

            <sensor type="camera" name="${direction}_${position}_cam">
                <update_rate>30.0</update_rate>
                <camera name="${direction}_${position}_cam">
                    <horizontal_fov>${fov}</horizontal_fov>
                    <image>
                        <width>800</width>
                        <height>600</height>
                        <format>R8G8B8</format>
                    </image>
                    <clip>
                        <near>0.02</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.001</stddev>
                    </noise>
                </camera>
                <plugin name="${direction}_${position}_cam_controller" filename="libgazebo_ros_camera.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>30.0</updateRate>
                    <cameraName>${robot_name}/${direction}/${position}</cameraName>
                    <imageTopicName>image_raw</imageTopicName>
                    <frameName>${direction}_${position}_optical_frame</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <!-- hackBase line cheks!!!!! -->
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>   
<!-- END MACROS FOR CREATE CAM IN THE GAZEBO -->
	
<!-- steer_wheel -->
	<xacro:steer_wheel name="joint_right_wheel_1" base_name="base_link" xyz="0.5 -0.375 -0.35" />
	<xacro:steer_wheel name="joint_left_wheel_1" base_name="base_link" xyz="0.5 0.375 -0.35" />
<!-- speed_wheel -->
	<xacro:speed_wheel name="joint_right_wheel_2" base_name="base_link" xyz="-0.5 -0.375 -0.35" />
	<xacro:speed_wheel name="joint_left_wheel_2" base_name="base_link" xyz="-0.5 0.375 -0.35" />

    <!-- <xacro:single_camera name="front_direction_left" direction="front" position="left" xyz="0.93 0.2 0.3" rpy="0 0 0" fov="1.3962634" />
    <xacro:single_camera name="front_direction_right" direction="front" position="right" xyz="0.93 -0.2 0.3" rpy="0 0 0" fov="1.3962634" /> -->

    <xacro:single_camera name="front_direction_left" direction="front" position="left" xyz="0.93 0.2 0.3" rpy="0 0 0" fov="1.3962634" />
    <xacro:single_camera name="front_direction_right" direction="front" position="right" xyz="0.93 -0.2 0.3" rpy="0 0 0" fov="1.3962634" />


    <xacro:single_camera name="backside_direction_left" direction="backside" position="left" xyz="-0.93 -0.2 0.3" rpy="0 0.0 ${degrees_180}" fov="1.3962634" />
    <xacro:single_camera name="backside_direction_right" direction="backside" position="right" xyz="-0.93 0.2 0.3" rpy="0 0.0 ${degrees_180}" fov="1.3962634" />

    <xacro:single_camera name="rightside_direction_left" direction="rightside" position="left" xyz="0.2 -0.38 0.3" rpy="0 0.0 -${degrees_90}" fov="1.3962634" />
    <xacro:single_camera name="rightside_direction_right" direction="rightside" position="right" xyz="-0.2 -0.38 0.3" rpy="0 0.0 -${degrees_90}" fov="1.3962634" />

    <xacro:single_camera name="leftside_direction_left" direction="leftside" position="left" xyz="-0.2 0.38 0.3" rpy="0 0.0 ${degrees_90}" fov="1.3962634" />
    <xacro:single_camera name="leftside_direction_right" direction="leftside" position="right" xyz="0.2 0.38 0.3" rpy="0 0.0 ${degrees_90}" fov="1.3962634" />
</robot>


