<?xml version="1.0" ?>
<robot name="tigra" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="length" value="1.85" />
<xacro:property name="width" value="0.75" />
<xacro:property name="heigth" value="0.6" />
<xacro:property name="mass" value="420" />

<xacro:property name="wheel_width" value="0.25" />
<xacro:property name="wheel_radius" value="0.25" />
<xacro:property name="wheel_mass" value="20" />

<xacro:property name="wheelbase" value="1.0" />
<xacro:property name="half_wheelbase" value="${wheelbase/2}" />
<xacro:property name="track_width" value="0.8" />

<xacro:property name="wheel_turn_limit" value="${pi/4}"/>
<xacro:property name="degrees_30" value="${pi/6}"/>
<xacro:property name="mid_wheel_turn_limit" value="${degrees_30}"/>

<xacro:property name="springStiffness" value="125000" />
<xacro:property name="springReference" value="0" />

<xacro:property name="lidar_mass" value="0.1" />
<xacro:property name="lidar_height" value="0.02"/>
<xacro:property name="lidar_radius" value="0.04"/>


<!-- base_footprint - base_link on floor -->
<link name="base_footprint">
</link>
<gazebo reference="base_footprint"/>
  
<xacro:arg name="pub_tf" default="true" />
  
<!-- inertia -->
<xacro:macro name="null_inertial">
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0"
               iyy="0.01" iyz="0"
               izz="0.01"/>
    </inertial>
</xacro:macro>

<xacro:macro name="base_inertial"
               params="width length height mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass * (width * width + height * height) / 12}"
               ixy="0" ixz="0"
               iyy="${mass * (length * length + height * height) / 12}"
               iyz="0"
               izz="${mass * (width * width + length * length) / 12}"/>
    </inertial>
</xacro:macro>

<xacro:macro name="wheel_inertial"
               params="r h mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass / 12 * (3 * r * r + h * h)}" ixy="0.0" ixz="0.0"
               iyy="${mass / 12 * (3 * r * r + h * h)}" iyz="0.0"
               izz="${mass / 2 * r * r}" />
    </inertial> 
</xacro:macro>
 
<!-- xacro base new -->
<link name="base_link">
    <visual>
     	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${length} ${width} ${heigth}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision name="base_collision">
    	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${length} ${width} ${heigth}"/>
        </geometry>
    </collision>
	<xacro:base_inertial
    width="${width}" length="${length}" 
	height="${heigth}" mass="${mass}" >
    <origin xyz="0 0 0" rpy="0 0 0" />
	</xacro:base_inertial>	
</link>


<!-- xacro wheel new -->
<xacro:macro name="wheels" params="name">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertial
          r="${wheel_radius}" h="${wheel_width}"
          mass="${wheel_mass}" >
	  <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      </xacro:wheel_inertial>
    </link>
</xacro:macro>

<!-- speed -->
<xacro:macro name="speed_wheel" params="name base_name xyz ">
    <xacro:wheels name="wheel_${name}" />

    <gazebo reference="${name}_spring_joint">
    	<implicitSpringDamper>true</implicitSpringDamper>
    	<springStiffness>${springStiffness}</springStiffness>
    	<springReference>${springReference}</springReference>
    </gazebo>

    <joint name="${name}_spring_joint" type="prismatic">
    <limit lower="-0.1" upper="0.1" effort="0" velocity="0"/> 
      <parent link="${base_name}"/>
      <child link="spring1_${name}"/>
	  <dynamics damping="0.0" friction="0.0"/>
	  <axis xyz="0 0 1"/>
    </joint>

    <link name="spring1_${name}">
      <xacro:null_inertial/>
    </link>   

    <joint name="${name}_speed_joint" type="continuous">
      <parent link="spring1_${name}"/> 
      <child link="wheel_${name}"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="500.0" velocity="10.0" />
    </joint>
</xacro:macro>

<!-- steer -->
<xacro:macro name="steer_wheel" params="name base_name xyz">
    <xacro:wheels name="wheel_${name}" />
 
    <gazebo reference="${name}_spring_joint">
    	<implicitSpringDamper>true</implicitSpringDamper>
    	<springStiffness>${springStiffness}</springStiffness>
    	<springReference>${springReference}</springReference>
    </gazebo>
    
    <joint name="${name}_spring_joint" type="prismatic">
    <limit lower="-0.1" upper="0.1" effort="0" velocity="0"/>
      <parent link="${base_name}"/>
      <child link="spring2_${name}"/>
	  <dynamics damping="0.0" friction="0.0"/>
	  <axis xyz="0 0 1"/>
    </joint>
   
    <link name="spring2_${name}">
      <xacro:null_inertial/>
    </link>
    
    <joint name="${name}_steer_joint" type="revolute">
      <limit lower="${-wheel_turn_limit}"
             upper="${wheel_turn_limit}"
             effort="1000" velocity="0"/>
      <parent link="spring2_${name}"/>
      <child link="steer_${name}"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

     <link name="steer_${name}">
      <xacro:null_inertial/>
    </link>
    
    <joint name="${name}_speed_joint" type="continuous">
      <parent link="steer_${name}"/>
      <child link="wheel_${name}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="500" velocity="10.0" />
    </joint>
</xacro:macro>

<!-- lidar -->
 <!-- Hokuyo Laser -->
  <link name="lidar_link">
    <xacro:wheel_inertial
        r="${lidar_radius}" h="${lidar_height}"
        mass="${lidar_mass}" >
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel_inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
      </geometry>
    </visual>
  </link>

  <gazebo reference="lidar_link">
    <material>Gazebo/Red</material>
    <sensor type="ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/tigra_description/laser/scan</topicName>
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <joint name="lidar_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 0.35" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="lidar_link"/>
  </joint>

  <joint name="base_footprint_2_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <!-- base_footprint - base_link on floor -->
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

<gazebo>
	<plugin name="tigra_interface_plugin" filename="libtigra_interface_plugin.so" >
		<robotName>tigra</robotName>
		<maxSteerRad>${mid_wheel_turn_limit}</maxSteerRad>
		<wheelbase>${wheelbase}</wheelbase>
		<wheelRadius>${wheel_radius}</wheelRadius>
		<trackWidth>${track_width}</trackWidth>
		<wheel_rl_joint_>joint_left_wheel_1_speed_joint</wheel_rl_joint_>
		<wheel_rr_joint_>joint_right_wheel_1_speed_joint</wheel_rr_joint_>
		<wheel_fl_joint_>joint_left_wheel_2_speed_joint</wheel_fl_joint_>
		<wheel_fr_joint_>joint_right_wheel_2_speed_joint</wheel_fr_joint_>
	</plugin>
</gazebo>


	
<!-- steer_wheel -->
	<xacro:steer_wheel name="joint_right_wheel_1" base_name="base_link" xyz="0.5 -0.375 -0.35" />
	<xacro:steer_wheel name="joint_left_wheel_1" base_name="base_link" xyz="0.5 0.375 -0.35" />
<!-- speed_wheel -->
	<xacro:speed_wheel name="joint_right_wheel_2" base_name="base_link" xyz="-0.5 -0.375 -0.35" />
	<xacro:speed_wheel name="joint_left_wheel_2" base_name="base_link" xyz="-0.5 0.375 -0.35" />
</robot>


