<?xml version="1.0" ?>
<robot name="tigra" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find tigra_description)/urdf/lidar.urdf.xacro" />
<xacro:include filename="$(find tigra_description)/urdf/wheels.urdf.xacro" />
  
<xacro:property name="length" value="1.85" />
<xacro:property name="width" value="0.75" />
<xacro:property name="heigth" value="0.6" />
<xacro:property name="mass" value="420" />

<xacro:property name="wheelbase" value="1.0" />
<xacro:property name="half_wheelbase" value="${wheelbase/2}" />
<xacro:property name="track_width" value="0.8" />

  
<!-- XACRO INERTIA -->
<xacro:macro name="base_inertial"
               params="width length height mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass * (width * width + height * height) / 12}"
               ixy="0" ixz="0"
               iyy="${mass * (length * length + height * height) / 12}"
               iyz="0"
               izz="${mass * (width * width + length * length) / 12}"/>
    </inertial>
</xacro:macro>
 
<!-- XACRO BASE -->
<link name="base_link">
    <visual>
     	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${length} ${width} ${heigth}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision name="base_collision">
    	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${length} ${width} ${heigth}"/>
        </geometry>
    </collision>
	<xacro:base_inertial
    width="${width}" length="${length}" 
	height="${heigth}" mass="${mass}" >
    <origin xyz="0 0 0" rpy="0 0 0" />
	</xacro:base_inertial>	
</link>

<!-- BASE FOOTPRINT-->
<link name="base_footprint"/>
<gazebo reference="base_footprint"/>
  
<joint name="base_footprint_2_link" type="fixed">
	<parent link="base_footprint"/>
	<child link="base_link"/>  
	<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
</joint>

<!-- GAZEBO -->
  <gazebo reference="lidar_link">
    <material>Gazebo/Red</material>
    <sensor type="ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/tigra_description/laser/scan</topicName>
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

<gazebo>
	<plugin name="tigra_interface_plugin" filename="libtigra_interface_plugin.so" >
		<robotName>tigra</robotName>
		<maxSteerRad>${mid_wheel_turn_limit}</maxSteerRad>
		<wheelbase>${wheelbase}</wheelbase>
		<wheelRadius>${wheel_radius}</wheelRadius>
		<trackWidth>${track_width}</trackWidth>
		<wheel_rl_joint_>joint_left_wheel_1_speed_joint</wheel_rl_joint_>
		<wheel_rr_joint_>joint_right_wheel_1_speed_joint</wheel_rr_joint_>
		<wheel_fl_joint_>joint_left_wheel_2_speed_joint</wheel_fl_joint_>
		<wheel_fr_joint_>joint_right_wheel_2_speed_joint</wheel_fr_joint_>
	</plugin>
</gazebo>

<!-- STEER WHEEL -->
	<xacro:steer_wheel name="joint_right_wheel_1" base_name="base_link" xyz="0.5 -0.375 -0.35" />
	<xacro:steer_wheel name="joint_left_wheel_1" base_name="base_link" xyz="0.5 0.375 -0.35" />
<!-- SPEED WHEEL -->
	<xacro:speed_wheel name="joint_right_wheel_2" base_name="base_link" xyz="-0.5 -0.375 -0.35" />
	<xacro:speed_wheel name="joint_left_wheel_2" base_name="base_link" xyz="-0.5 0.375 -0.35" />
</robot>


