local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  transform_rolerance: 0.5
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: true
  
  width: 20.0
  height: 20.0
  resolution: 0.05

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}      
    # - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: depth_obstacle_layer, type: "costmap_2d::VoxelLayer"}
    # - {name: head_stereo_obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
