<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="length" value="1.85" />
    <xacro:property name="width" value="0.75" />
    <xacro:property name="heigth" value="0.6" />
    <xacro:property name="mass" value="420" />
    <xacro:property name="wheel_width" value="0.25" />
    <xacro:property name="wheel_radius" value="0.25" />
    <xacro:property name="wheel_mass" value="20" />
    <xacro:property name="wheel_turn_limit" value="${pi/4}" />

	<xacro:property name="wheelbase" value="1.0" />
	<xacro:property name="half_wheelbase" value="${wheelbase/2}" />
	<xacro:property name="track_width" value="0.8" />

    <xacro:property name="lidar_location" value="${heigth/2+0.01}" />

	<xacro:property name="odom_frame" value="odom_wheel" />

    <xacro:arg name="pub_tf" default="true" />
    <xacro:arg name="robot_name" default="tigra" />
</robot>
