
footprint: [ [-0.9,-0.55], [0.9,-0.55], [0.9,0.55], [-0.9,0.55] ]

transform_tolerance: 0.2
map_type: costmap

inflation_layer:
    enabled:              true
    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.25  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
    enabled:              true
    map_topic:            "map"

obstacle_layer:
    enabled: true
    obstacle_range: 7.5
    raytrace_range: 6.0
    track_unknown_space: false
    combination_method: 1

    observation_sources: stereo_cam_vision radar_obst
    stereo_cam_vision:
        data_type: PointCloud2
        topic: stereo/points2
        marking: true
        clearing: true

    radar_obst:
        data_type: PointCloud2
        topic: mmWaveDataHdl/RScan
        marking: true
        clearing: true

