
recovery_behaviors:
    - name: aggressive_reset
      type: clear_costmap_recovery/ClearCostmapRecovery

# Configuration for recovery behaviors
aggressive_reset:
  # When doing an aggressive reset, remove all voxels from the
  # costmap.
    reset_distance: 0.01

# See also costmap_common_params.yaml for additional parameters set
# for the two costmaps.
local_costmap:
    global_frame: /map
    robot_base_frame: base_link

    update_frequency: 5
    publish_frequency: 2
    static_map: false
    rolling_window: true
    width: 15
    height: 15
    resolution: 0.1
    transform_tolerance: 0.5

    plugins:
    # - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}

global_costmap:
    global_frame: /map
    robot_base_frame: base_link
    update_frequency: 5
    publish_frequency: 1
    static_map: false

    width: 100
    height: 100
    resolution: 0.05
    origin_x: -50.0
    origin_y: -50.0

    transform_tolerance: 0.5
    
    # plugins:
    # - {name: static_layer,          type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
    # - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}


TebLocalPlannerROS:
    odom_topic: odom

    # Trajectory

    teb_autosize: True
    dt_ref: 0.3
    dt_hysteresis: 0.1
    global_plan_overwrite_orientation: True
    max_global_plan_lookahead_dist: 5.0
    feasibility_check_no_poses: 5

    # Robot
         
    wheelbase: 1.3
    cmd_angle_instead_rotvel: True

    max_vel_x: 0.7
    max_vel_x_backwards: 0.7
    max_vel_theta: 0.3
    acc_lim_x: 0.3
    acc_lim_theta: 0.5
    min_turning_radius: 1.8
    footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
        type: "line"
        # radius: 0.2 # for type "circular"
        line_start: [-0.9, 0.0] # for type "line"
        line_end: [0.9, 0.0] # for type "line"
        # front_offset: 0.2 # for type "two_circles"
        # front_radius: 0.2 # for type "two_circles"
        # rear_offset: 0.2 # for type "two_circles"
        # rear_radius: 0.2 # for type "two_circles"
        # vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

    # GoalTolerance

    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.1
    free_goal_vel: False

    # Obstacles

    min_obstacle_dist: 1.2
    include_costmap_obstacles: True
    costmap_obstacles_behind_robot_dist: 1.0
    obstacle_poses_affected: 5
    # costmap_converter_plugin: ""
    # costmap_converter_spin_thread: True
    # costmap_converter_rate: 5

    # Optimization

    no_inner_iterations: 5
    no_outer_iterations: 4
    optimization_activate: True
    optimization_verbose: False
    penalty_epsilon: 0.1
    weight_max_vel_x: 2
    weight_max_vel_theta: 1
    weight_acc_lim_x: 1
    weight_acc_lim_theta: 1
    weight_kinematics_nh: 1000
    weight_kinematics_forward_drive: 1
    weight_kinematics_turning_radius: 1
    weight_optimaltime: 1
    weight_obstacle: 50
    weight_dynamic_obstacle: 10 # not in use yet
    # selection_alternative_time_cost: False # not in use yet

    # Homotopy Class Planner

    enable_homotopy_class_planning: True
    enable_multithreading: True
    simple_exploration: False
    max_number_classes: 4
    roadmap_graph_no_samples: 15
    roadmap_graph_area_width: 5
    h_signature_prescaler: 0.5
    h_signature_threshold: 0.1
    obstacle_keypoint_offset: 0.1
    obstacle_heading_threshold: 0.45
    visualize_hc_graph: False

